export default {
    'app.contentList': 'Content List',
    'app.selectCollectionType': 'Select Collection Type',
    'app.info':'Info',
    'app.content': 'Content',
    'app.contentsButton': 'contents',
    'app.contentButton': 'content',
    'app.name':'Name',
    'app.created':'Created by',
    'app.lastEdited':'Last edited',
    'app.createdDate':'Created date',
    'app.selectDefaultTemplate':'Select default template*',
    'app.addExistingContent':'Add existing ',
    'app.addNewContent':'Add new content',
    'app.select':'Select',
    'app.selectCollection':'Choose an option',
    'app.widgetConfiguration':'Widget Configuration',
    'app.queryFilter':'Query Filter',
    'app.cancel':'Cancel',
    'app.savedAsQuery':'Saved as Query',
    'app.saveAsQuery':'Save as Query',
    'app.saveAsListOfContents':'Save as list of Contents',
    'app.select':'Select',
    // 'app.lastEdited':'Last Edited',
    'app.createdEdited':'Created Edited',
    'app.searchContentByName':'Filter By Name...',
    'app.remove':'Remove',
    'app.query':' Query',
    'app.selectTemplate':'Select Template',
    'app.edit':'Edit',
    'app.queryFilter':' Query Filter',
    'app.search':'Search',
    'app.applyToAllContents':'Apply to all contents',
    'app.noMatchesFound': 'No matches found',
    'app.noDataAvailable': 'No data available',
    'app.firstPage': 'First Page',
    'app.previousPage': 'Previous Page',
    'app.currentPage': 'Current Page',
    'app.nextPage': 'Next Page',
    'app.lastPage': 'Last Page',
    'app.perPage': 'per page',
    'app.of': 'of',
    }