export default {
    'app.contentList': 'Content Elenco',
    'app.selectCollectionType': 'Seleziona Tipo di raccolta',
    'app.info':'Informazioni',
    'app.content': ' Contenuto',
    'app.contentsButton': 'contenuti',
    'app.contentButton': 'contenuto',
    'app.name':'Nome',
    'app.created':'Creata da',
    'app.lastEdited':'Ultima modifica',
    'app.createdDate':'Creata Data',
    'app.selectDefaultTemplate':'Seleziona il modello predefinito*',
    'app.addExistingContent':'Aggiungi esistente',
    'app.addNewContent':'Aggiungi nuovo contenuto',
    'app.select':'Seleziona',
    'app.selectCollection':"Scegliere un'opzione",
    'app.widgetConfiguration':'Configurazione del widget',
    'app.queryFilter':'Filtro di query',
    'app.cancel':'Annulla',
    'app.savedAsQuery':'Salvato come query',
    'app.saveAsQuery':'Salva come query',
    'app.saveAsListOfContents':'Salva come elenco di contenuti',
    'app.select':'Selezionare',
    // 'app.lastEdited':'Ultima modifica',
    'app.createdEdited':'Data di Creazione',
    'app.searchContentByName':'Filtra per nome',
    'app.remove':'Rimuovere',
    'app.query':'Domanda',
    'app.selectTemplate':'Seleziona Modello',
    'app.edit':'modificare',
    'app.query':'Filtro di query',
    'app.search':'Ricerca',
    'app.applyToAllContents':'Applica a tutti i contenuti',
    'app.noMatchesFound': 'Nessun risultato trovato',
    'app.noDataAvailable': 'Nessun dato disponibile',
    'app.firstPage': 'Prima pagina',
    'app.previousPage': 'Pagina precedente',
    'app.currentPage': 'Pagina corrente',
    'app.nextPage': 'Pagina successiva',
    'app.lastPage': 'Ultima pagina',
    'app.perPage': 'per pagina',
    'app.of': 'di',
    }

    //'app.content': 'Contenuto',